name: first workflow
# start
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
         node-version: '23'
        
      - name: Install dependencies
        run: |
          cd allvest
          npm install
         
      - name: Build project
        run: |
          cd allvest
          npm run build

